---
title: "Venue, food and social"
---

## The venue

::: callout-note
-   Note our new venue! We will be hosting in-person participants at 275 George Street, Brisbane.
:::

The venue (275 George Street, Brisbane) is the location of Fisheries Queensland's head office. It is a short, 550m walk from Central train station, or 600m to Roma Street train station.

```{=html}
<div style="display: flex; justify-content: center; margin: 20px 0;">
<iframe 
  src="https://www.google.com/maps/d/u/1/embed?mid=1Z0lJuwHDei4dmE-sYw6GFVwbO0t8erQ&ehbc=2E312F&noprof=1" 
  width="640" 
  height="480">
</iframe>
</div>
```
All public transport fares in Queensland cost 50 cents. Contactless payment is available on all South East Queensland (SEQ) trains, trams, ferries and buses—you can use your digital or physical bank card to tap on and off.

The workshop will be held in a boardroom on Level 14. Participants are to meet on the ground floor and a designated Queensland Government staff member will escort you in.

Wi-Fi will be available on site.

## Accessibility

We want to make sure our event is equitable and that everyone is included.

If there’s something we can do to make the event more accessible to you, please let us know.

You can email us at [stockassessmentcop\@gmail.com](mailto:stockassessmentcop@gmail.com).

## Census

Tuesday night is Census night! If you're staying away from home on Tuesday night to attend our workshop, read up on how you should complete the census. Note the following instructions taken from the [ABS website](https://info.census.abs.gov.au/help/completing-census-where-you-are/travelling){target="_blank"}:

**Staying at a hotel, motel, or other holiday accommodation (including Bed and Breakfasts)**

* If you’re staying in a hotel, motel or other holiday accommodation away from home, you’ll need to complete a Census form.
* The accommodation staff will hand out Census forms to all guests and collect completed forms. Please check with staff if you don’t get a form. 
* If you prefer, you can [complete the Census online](https://start.census.abs.gov.au/){target="_blank"} wherever you can access the internet. Use the login details on the front of your paper form or you can [get a Census number](https://form.census.abs.gov.au/get-census-number){target="_blank"}. You'll need to use a mobile phone to complete the process of getting a Census number and password.

**Staying in short-term accommodation (Airbnb, Stayz or a holiday rental)**

* You'll need to complete a Census form wherever you are staying on Census night.
* If you’re staying at short-term accommodation such as an Airbnb or Stayz, the easiest way to complete your Census is online. 
* You can [get a Census number](https://form.census.abs.gov.au/get-census-number){target="_blank"} and complete your Census online wherever you have access to the internet. You'll need to use a mobile phone to complete the process of getting a Census number and password.

## Food and drink

#### Tea and coffee

In person attendees, please bring your own coffee cup or mug, if possible. We will provide basic tea and coffee and biscuits for morning/afternoon tea. If you prefer non-instant coffee, please BYO, noting there is a cafe on the ground floor of the building.

#### Lunch

There are ample eating options nearby.

#### Dinner

Group dinners have been organised for each night from Monday to Thursday. These dinners are optional and will be pay-your-own-way. These dinners will be held at the following venues from 6pm:

-   *Monday 10th August:* Ahmet's Turkish Restaurant, Shop 10/168 Grey Street
-   *Tuesday 11th August*: The Spaghetti House, corner Little Stanley and Grey St
-   *Wednesday 12th August*: Poca Madre Restaurant, Shop 15/14 Little Stanley Street
-   *Thursday 13th August*: Transcontinental Hotel (back deck), 482 George Street

## Social events

If anyone is around on the evening of Friday, 14th August, and would like to imbibe some popular culture, **we will gauge interest for a group soiree(s)** to:

-   [Night Feast at Brisbane Powerhouse](https://www.nightfeast.com.au/about/)—Set within a temporary village of Queensland fretwork, Cantonese lacquer and luminous neon, a selection of Brisbane’s top chefs will feature their exclusive dishes

-   [The Book of Mormon](https://thebookofmormonmusical.com.au/tickets/brisbane/) (comedy musical)—7:30pm, Glasshouse Theatre. Available tickets range from \$189-\$249

We will look to confirm attendance for these at the start of the workshop.

For the sports fans, sadly, there is no AFL or NRL action until Saturday 15th. The Brisbane Lions play the Gold Coast Suns at the Gabba on Saturday night, and there is a rugby double-header at Suncorp Stadium on the same evening—NRLW Broncos vs Roosters, and NRL Broncos vs Warriors.

## 
